TEAM_ALIASES = {
    "hawks": "Atlanta Hawks",
    "atlanta hawks": "Atlanta Hawks",
    "celtics": "Boston Celtics",
    "boston celtics": "Boston Celtics",
    "nets": "Brooklyn Nets",
    "brooklyn nets": "Brooklyn Nets",
    "hornets": "Charlotte Hornets",
    "charlotte hornets": "Charlotte Hornets",
    "bulls": "Chicago Bulls",
    "chicago bulls": "Chicago Bulls",
    "cavs": "Cleveland Cavaliers",
    "cavs cavaliers": "Cleveland Cavaliers",
    "cavaliers": "Cleveland Cavaliers",
    "cleveland cavaliers": "Cleveland Cavaliers",
    "mavs": "Dallas Mavericks",
    "mavericks": "Dallas Mavericks",
    "dallas mavericks": "Dallas Mavericks",
    "nuggets": "Denver Nuggets",
    "denver nuggets": "Denver Nuggets",
    "pistons": "Detroit Pistons",
    "detroit pistons": "Detroit Pistons",
    "warriors": "Golden State Warriors",
    "golden state warriors": "Golden State Warriors",
    "rockets": "Houston Rockets",
    "houston rockets": "Houston Rockets",
    "pacers": "Indiana Pacers",
    "indiana pacers": "Indiana Pacers",
    "clippers": "LA Clippers",
    "la clippers": "LA Clippers",
    "los angeles clippers": "LA Clippers",
    "lakers": "Los Angeles Lakers",
    "los angeles lakers": "Los Angeles Lakers",
    "grizzlies": "Memphis Grizzlies",
    "memphis grizzlies": "Memphis Grizzlies",
    "heat": "Miami Heat",
    "miami heat": "Miami Heat",
    "bucks": "Milwaukee Bucks",
    "milwaukee bucks": "Milwaukee Bucks",
    "timberwolves": "Minnesota Timberwolves",
    "wolves": "Minnesota Timberwolves",
    "minnesota timberwolves": "Minnesota Timberwolves",
    "pelicans": "New Orleans Pelicans",
    "new orleans pelicans": "New Orleans Pelicans",
    "knicks": "New York Knicks",
    "new york knicks": "New York Knicks",
    "thunder": "Oklahoma City Thunder",
    "okc": "Oklahoma City Thunder",
    "oklahoma city thunder": "Oklahoma City Thunder",
    "magic": "Orlando Magic",
    "orlando magic": "Orlando Magic",
    "sixers": "Philadelphia 76ers",
    "76ers": "Philadelphia 76ers",
    "philadelphia 76ers": "Philadelphia 76ers",
    "suns": "Phoenix Suns",
    "phoenix suns": "Phoenix Suns",
    "blazers": "Portland Trail Blazers",
    "trail blazers": "Portland Trail Blazers",
    "portland trail blazers": "Portland Trail Blazers",
    "kings": "Sacramento Kings",
    "sacramento kings": "Sacramento Kings",
    "spurs": "San Antonio Spurs",
    "san antonio spurs": "San Antonio Spurs",
    "raptors": "Toronto Raptors",
    "toronto raptors": "Toronto Raptors",
    "jazz": "Utah Jazz",
    "utah jazz": "Utah Jazz",
    "wizards": "Washington Wizards",
    "washington wizards": "Washington Wizards"
}

TEAM_ALIASES.update({
    "atl": "Atlanta Hawks",
    "bos": "Boston Celtics",
    "bkn": "Brooklyn Nets",
    "cha": "Charlotte Hornets",
    "chi": "Chicago Bulls",
    "cle": "Cleveland Cavaliers",
    "dal": "Dallas Mavericks",
    "den": "Denver Nuggets",
    "det": "Detroit Pistons",
    "gsw": "Golden State Warriors",
    "hou": "Houston Rockets",
    "ind": "Indiana Pacers",
    "lac": "LA Clippers",
    "lal": "Los Angeles Lakers",
    "mem": "Memphis Grizzlies",
    "mia": "Miami Heat",
    "mil": "Milwaukee Bucks",
    "min": "Minnesota Timberwolves",
    "nop": "New Orleans Pelicans",
    "nyk": "New York Knicks",
    "okc": "Oklahoma City Thunder",
    "orl": "Orlando Magic",
    "phi": "Philadelphia 76ers",
    "phx": "Phoenix Suns",
    "por": "Portland Trail Blazers",
    "sac": "Sacramento Kings",
    "sas": "San Antonio Spurs",
    "tor": "Toronto Raptors",
    "uta": "Utah Jazz",
    "was": "Washington Wizards",
})

TEAM_IDS = {
    "Atlanta Hawks": 1610612737,
    "Boston Celtics": 1610612738,
    "Brooklyn Nets": 1610612751,
    "Charlotte Hornets": 1610612766,
    "Chicago Bulls": 1610612741,
    "Cleveland Cavaliers": 1610612739,
    "Dallas Mavericks": 1610612742,
    "Denver Nuggets": 1610612743,
    "Detroit Pistons": 1610612765,
    "Golden State Warriors": 1610612744,
    "Houston Rockets": 1610612745,
    "Indiana Pacers": 1610612754,
    "LA Clippers": 1610612746,
    "Los Angeles Lakers": 1610612747,
    "Memphis Grizzlies": 1610612763,
    "Miami Heat": 1610612748,
    "Milwaukee Bucks": 1610612749,
    "Minnesota Timberwolves": 1610612750,
    "New Orleans Pelicans": 1610612740,
    "New York Knicks": 1610612752,
    "Oklahoma City Thunder": 1610612760,
    "Orlando Magic": 1610612753,
    "Philadelphia 76ers": 1610612755,
    "Phoenix Suns": 1610612756,
    "Portland Trail Blazers": 1610612757,
    "Sacramento Kings": 1610612758,
    "San Antonio Spurs": 1610612759,
    "Toronto Raptors": 1610612761,
    "Utah Jazz": 1610612762,
    "Washington Wizards": 1610612764
}